# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_interceptor/testing/protos/dummy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="grpc_interceptor/testing/protos/dummy.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n+grpc_interceptor/testing/protos/dummy.proto"\x1d\n\x0c\x44ummyRequest\x12\r\n\x05input\x18\x01 \x01(\t"\x1f\n\rDummyResponse\x12\x0e\n\x06output\x18\x01 \x01(\t28\n\x0c\x44ummyService\x12(\n\x07\x45xecute\x12\r.DummyRequest\x1a\x0e.DummyResponseb\x06proto3',
)


_DUMMYREQUEST = _descriptor.Descriptor(
    name="DummyRequest",
    full_name="DummyRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="input",
            full_name="DummyRequest.input",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=47,
    serialized_end=76,
)


_DUMMYRESPONSE = _descriptor.Descriptor(
    name="DummyResponse",
    full_name="DummyResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="output",
            full_name="DummyResponse.output",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=78,
    serialized_end=109,
)

DESCRIPTOR.message_types_by_name["DummyRequest"] = _DUMMYREQUEST
DESCRIPTOR.message_types_by_name["DummyResponse"] = _DUMMYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DummyRequest = _reflection.GeneratedProtocolMessageType(
    "DummyRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _DUMMYREQUEST,
        "__module__": "grpc_interceptor.testing.protos.dummy_pb2"
        # @@protoc_insertion_point(class_scope:DummyRequest)
    },
)
_sym_db.RegisterMessage(DummyRequest)

DummyResponse = _reflection.GeneratedProtocolMessageType(
    "DummyResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _DUMMYRESPONSE,
        "__module__": "grpc_interceptor.testing.protos.dummy_pb2"
        # @@protoc_insertion_point(class_scope:DummyResponse)
    },
)
_sym_db.RegisterMessage(DummyResponse)


_DUMMYSERVICE = _descriptor.ServiceDescriptor(
    name="DummyService",
    full_name="DummyService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=111,
    serialized_end=167,
    methods=[
        _descriptor.MethodDescriptor(
            name="Execute",
            full_name="DummyService.Execute",
            index=0,
            containing_service=None,
            input_type=_DUMMYREQUEST,
            output_type=_DUMMYRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DUMMYSERVICE)

DESCRIPTOR.services_by_name["DummyService"] = _DUMMYSERVICE

# @@protoc_insertion_point(module_scope)
