# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_interceptor/testing/protos/dummy.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="grpc_interceptor/testing/protos/dummy.proto",
    package="",
    syntax="proto3",
    serialized_pb=_b(
        '\n+grpc_interceptor/testing/protos/dummy.proto"\x1d\n\x0c\x44ummyRequest\x12\r\n\x05input\x18\x01 \x01(\t"\x1f\n\rDummyResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2\xe8\x01\n\x0c\x44ummyService\x12(\n\x07\x45xecute\x12\r.DummyRequest\x1a\x0e.DummyResponse\x12\x36\n\x13\x45xecuteClientStream\x12\r.DummyRequest\x1a\x0e.DummyResponse(\x01\x12\x36\n\x13\x45xecuteServerStream\x12\r.DummyRequest\x1a\x0e.DummyResponse0\x01\x12>\n\x19\x45xecuteClientServerStream\x12\r.DummyRequest\x1a\x0e.DummyResponse(\x01\x30\x01\x62\x06proto3'
    ),
)


_DUMMYREQUEST = _descriptor.Descriptor(
    name="DummyRequest",
    full_name="DummyRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="input",
            full_name="DummyRequest.input",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=47,
    serialized_end=76,
)


_DUMMYRESPONSE = _descriptor.Descriptor(
    name="DummyResponse",
    full_name="DummyResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="output",
            full_name="DummyResponse.output",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=78,
    serialized_end=109,
)

DESCRIPTOR.message_types_by_name["DummyRequest"] = _DUMMYREQUEST
DESCRIPTOR.message_types_by_name["DummyResponse"] = _DUMMYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DummyRequest = _reflection.GeneratedProtocolMessageType(
    "DummyRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DUMMYREQUEST,
        __module__="grpc_interceptor.testing.protos.dummy_pb2"
        # @@protoc_insertion_point(class_scope:DummyRequest)
    ),
)
_sym_db.RegisterMessage(DummyRequest)

DummyResponse = _reflection.GeneratedProtocolMessageType(
    "DummyResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DUMMYRESPONSE,
        __module__="grpc_interceptor.testing.protos.dummy_pb2"
        # @@protoc_insertion_point(class_scope:DummyResponse)
    ),
)
_sym_db.RegisterMessage(DummyResponse)


_DUMMYSERVICE = _descriptor.ServiceDescriptor(
    name="DummyService",
    full_name="DummyService",
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=112,
    serialized_end=344,
    methods=[
        _descriptor.MethodDescriptor(
            name="Execute",
            full_name="DummyService.Execute",
            index=0,
            containing_service=None,
            input_type=_DUMMYREQUEST,
            output_type=_DUMMYRESPONSE,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name="ExecuteClientStream",
            full_name="DummyService.ExecuteClientStream",
            index=1,
            containing_service=None,
            input_type=_DUMMYREQUEST,
            output_type=_DUMMYRESPONSE,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name="ExecuteServerStream",
            full_name="DummyService.ExecuteServerStream",
            index=2,
            containing_service=None,
            input_type=_DUMMYREQUEST,
            output_type=_DUMMYRESPONSE,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name="ExecuteClientServerStream",
            full_name="DummyService.ExecuteClientServerStream",
            index=3,
            containing_service=None,
            input_type=_DUMMYREQUEST,
            output_type=_DUMMYRESPONSE,
            options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DUMMYSERVICE)

DESCRIPTOR.services_by_name["DummyService"] = _DUMMYSERVICE

# @@protoc_insertion_point(module_scope)
